# Generated by Django 4.2 on 2023-05-07 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_test_up'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='up',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='Up',
        ),
    ]
