# Generated by Django 4.2 on 2023-05-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_posts_author_posts_synopsis_posts_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
